<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MageMobile Registration</title>
</head>
<body>
<form action="saveuser" method="post" id="save">
    Enter your best email address: <br>
    <input type="text" name="email">
    Enter your website URL: <br>
    <input type="text" name="url">
    Enter your access token: <br>
    <input type="text" name="access_token">
    <br><br>
    <input type="Submit" value="Submit">
</form>
</body>
</html>